### ISSUE TITLE
--starting doesn't seem to work

### ISSUE THREAD

**Issue by mwarkentin** [apurvasingh/connector#3]
Hi there, not sure if this is the right place to log issues with https://github.com/cloudpassage/connector, but there's no way to do so on that repo.

Example:

```
python halo_events.py --auth cloudpassage.auth --starting 2017-09-29T05:00Z --configdir=./configs --jsonfile=./events.log
Wrote: 2017-01-14T11:18:26.432Z to 2017-01-15T17:18:19.303Z
```

Changing [this line](https://github.com/cloudpassage/connector/blob/master/lib/event.py#L174) from `initial_event_id = self.latest_event("1", "", "1")["events"][0]["id"]` to `initial_event_id = self.latest_event("1", self.args["starting"], "1")["events"][0]["id"]` allows it to work correctly:

```
python halo_events.py --auth cloudpassage.auth --starting 2017-09-29T12:00Z --configdir=./configs --jsonfile=./events.log
Wrote: 2017-09-29T12:01:04.537Z to 2017-09-29T15:24:47.012Z
```

However that breaks things if you **don't** pass the `--starting` option:

```
python halo_events.py --auth cloudpassage.auth --configdir=./configs --jsonfile=./events.log
/v1/events?sort_by=created_at.desc&per_page=1&page=1&since=./configs
Traceback (most recent call last):
  File "halo_events.py", line 18, in <module>
    main()
  File "halo_events.py", line 14, in main
    event.retrieve_events()
  File "/opt/cloudpassage/bin/lib/event.py", line 175, in retrieve_events
    initial_event_id = self.latest_event("1", self.args["starting"], "1")["events"][0]["id"]
  File "/opt/cloudpassage/bin/lib/event.py", line 71, in latest_event
    return api.get(url)
  File "/usr/local/lib/python2.7/dist-packages/cloudpassage/http_helper.py", line 99, in get
    raise exception
cloudpassage.exceptions.CloudPassageValidation: 422 {"message":"Validation Failed","errors":[{"field":"since","value":"./configs","code":"is invalid","details":"Since is invalid"}]}
```

You can see that for some reason `self.args["starting"]` seems to be set to the value for `--configdir` if I don't set it myself.

I'd be happy to provide a PR, but am a bit stuck on the args thing right now.

CC @eatwithforks

**Comment by eatwithforks** [comment]
Hi Michael,

For your first example:
`python halo_events.py --auth cloudpassage.auth --starting 2017-09-29T05:00Z --configdir=./configs --jsonfile=./events.log
Wrote: 2017-01-14T11:18:26.432Z to 2017-01-15T17:18:19.303Z`

Can you check if your configdir already includes a 'checkpoint' timestamp?
If so, then the starting argument will be ignored and will start pulling from the checkpoint file instead. 

To clarify (please look at the following):
`connector/configs (master) $ ls
README		cef.yml		leef.yml	portal.yml	rsyslog.yml`

We can see that I don't have a checkpoint timestamp file in the configs directory.

`connector (master) $ python halo_events.py --auth=test_auth --starting=2017-09-28 --configdir=./configs --jsonfile=./events.log
Wrote: 2017-09-28T00:05:52.156Z to 2017-09-29T15:53:50.480Z`

After this run completes, a checkpoint timestamp file will be automatically saved into the configs directory. Subsequent runs will start from the checkpoint and ignore your --starting argument.

`connector (master) $ ls configs/
README					cef.yml					portal.yml
abc123abc_2017-09-29T15+53+50.480Z	leef.yml				rsyslog.yml`


The reason for the checkpoint file prioritizing over --starting is so users won't miss a single event if they stop/continue the program. 

If you want to start from 2017-09-28, you'll have to delete the checkpoint file from your configsdir.

Please let me know if I misunderstood your question or if this makes sense. Thanks!

**Comment by mwarkentin** [comment]
Thanks @eatwithforks - can you link or provide the git commit that you're working off in your example above? Is it latest master? I'd like to compare the code with what I'm running (https://github.com/cloudpassage/connector/commit/9748a26a2d006493d91b679eb8c8f9ce91c3a5ba).

I believe my example was with the config timestamp file removed - our use case is that we want to use the `--starting` option when a new logging server is launched so that we're not flooding our sumologic with duplicate events.

Let me launch a fresh instance and I'll provide some examples of what I'm seeing without the config file.

**Comment by mwarkentin** [comment]
Closing.. looks like you were right and I had a config file added to the AMI I launched from. After cleaning that up things worked as expected. 

```
root@ip-10-0-0-29:/opt/cloudpassage/bin# ll configs/
total 40
drwxr-xr-x 2 root root 4096 Sep 29 17:50 ./
drwx------ 5 root root 4096 Sep 29 17:47 ../
-r-x------ 1 root root 4939 Sep 28 20:41 cef.yml*
-r-x------ 1 root root 6148 Sep 28 20:41 .DS_Store*
-r-x------ 1 root root 4917 Sep 28 20:41 leef.yml*
-r-x------ 1 root root  213 Sep 28 20:41 portal.yml*
-r-x------ 1 root root    0 Sep 28 20:41 README*
-r-x------ 1 root root  850 Sep 28 20:41 rsyslog.yml*
root@ip-10-0-0-29:/opt/cloudpassage/bin# time python halo_events.py --auth cloudpassage.auth --starting 2017-09-29T17:00Z --configdir=./configs --jsonfile=./events.log
Wrote: 2017-09-29T17:01:04.783Z to 2017-09-29T17:50:25.819Z
```
